In [47]:
import sys
import numpy as np

Basic Numpy Arrays

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2.])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2] # Start stop step

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [13]:
b[[0, 2, -1]]

array([0., 1., 2.])

Array Types

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int32')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [18]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [19]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [20]:
c = np.array(['a', 'b', 'c'])

In [22]:
c.dtype

dtype('<U1')

In [23]:
d = np.array([{'a' : 1}, sys])

In [27]:
d.dtype

dtype('O')

Dimensions and shapes

In [28]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A.shape

(2, 3)

In [29]:
A.ndim

2

In [30]:
A.size

6

In [40]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [51]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [52]:
B.shape

(2, 2, 3)

In [53]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [66]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [67]:
C.dtype

dtype('int32')

In [68]:
C.shape

(2, 2, 3)

In [69]:
C.size

12

In [70]:
type(C[0])

numpy.ndarray

Indexing and Slicing of Matrices

In [71]:
# Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A[1]

array([4, 5, 6])

In [72]:
A[1][0]

4

In [73]:
# A[d1, d2, d3, d4]

In [79]:
A[1, 0]

4

In [80]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [82]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [83]:
A[:2, 2:]

array([[3],
       [6]])

In [84]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
A[1] = np.array([10, 10, 10])

In [86]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [87]:
A[2] = 99

In [88]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary statistics

In [89]:
a = np.array([1, 2, 3, 4])

In [90]:
a.sum()

10

In [91]:
a.mean()

2.5

In [92]:
a.std()

1.118033988749895

In [95]:
a.var()

1.25

In [96]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [97]:
A.sum()

45

In [98]:
A.mean()

5.0

In [99]:
A.sum(axis=0) #Ustunlar bo'yicha yig'indi

array([12, 15, 18])

In [100]:
A.std()

2.581988897471611

In [101]:
A.sum(axis=1)

array([ 6, 15, 24])

In [102]:
A.mean(axis=0)

array([4., 5., 6.])

In [103]:
A.mean(axis=1)

array([2., 5., 8.])

In [104]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [105]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

Broadcasting and Vectorized operations

In [106]:
a = np.arange(4)

In [107]:
a

array([0, 1, 2, 3])

In [108]:
a + 10

array([10, 11, 12, 13])

In [110]:
a*10

array([ 0, 10, 20, 30])

In [111]:
a

array([0, 1, 2, 3])

In [116]:
a += 100

In [117]:
a

array([300, 301, 302, 303])

In [118]:
l = [0, 1, 2, 3]

In [119]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [121]:
a = np.arange(4)

In [122]:
a

array([0, 1, 2, 3])

In [123]:
b = np.array([10, 10, 10, 10])

In [124]:
b

array([10, 10, 10, 10])

In [125]:
a + b

array([10, 11, 12, 13])

In [126]:
a*b

array([ 0, 10, 20, 30])

Boolean arrays
(Also called masks)

In [127]:
a = np.arange(4)

In [128]:
a

array([0, 1, 2, 3])

In [129]:
a[0], a[-1]

(0, 3)

In [130]:
a[[True, False, False, True]]

array([0, 3])

In [131]:
a

array([0, 1, 2, 3])

In [132]:
a >= 2

array([False, False,  True,  True])

In [133]:
a[a >= 2]

array([2, 3])

In [134]:
a.mean()

1.5

In [136]:
a[a > a.mean()]

array([2, 3])

In [137]:
a[~(a > a.mean())] # "~" mantiqiy inkor amali

array([0, 1])

In [138]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [139]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [140]:
A = np.random.randint(100, size=(3,3)) #Tasodifiy 3x3 matritsa

In [141]:
A

array([[25, 12, 98],
       [60, 17, 72],
       [77,  2, 30]])

A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

In [143]:
A > 30

array([[False, False,  True],
       [ True, False,  True],
       [ True, False, False]])

In [144]:
A[A> 30]

array([98, 60, 72, 77])

Linear Algebra

In [145]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [146]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [147]:
A.dot(B) # matritsalarni ko'paytirish

array([[20, 14],
       [56, 41],
       [92, 68]])

In [148]:
B.T #Transponirlangan matritsa

array([[6, 4, 2],
       [5, 3, 1]])

In [149]:
A @ B # matritsalarni ko'paytirish

array([[20, 14],
       [56, 41],
       [92, 68]])

Size of objects in Memory
Int, floats

In [150]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [151]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [153]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [154]:
np.dtype(float).itemsize

8

Lists are even larger

In [155]:
# A one-element list
sys.getsizeof([1])

64

In [156]:
# An array of one element in numpy
np.array([1]).nbytes

4

And performance is also important

In [157]:
l = list(range(100000))

In [158]:
a = np.arange(100000)

In [159]:
%time np.sum( a ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


216474736

In [160]:
%time np.sum([ x ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 8.39 ms


333328333350000

Useful Numpy functions

In [162]:
np.random.random(size=2)

array([0.24277747, 0.15261056])

In [163]:
np.random.normal(size=2)

array([-1.64185374,  1.72359991])

In [164]:
np.random.rand(2,4)

array([[0.10898916, 0.00885852, 0.12483531, 0.72380283],
       [0.76811634, 0.65750521, 0.18851267, 0.75561423]])

arange

In [165]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [167]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape

In [168]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [169]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

linspace

In [170]:
np.linspace(0, 1, 5) # ma'lum oraliqdagi sonlarni teng n qismlarga bo'laklab tashlash

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [173]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [174]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros, ones, empty

In [175]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [176]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [179]:
np.zeros((3, 3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [180]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [181]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [182]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

identity and eye

In [184]:
np.identity(3) # birlik matritsa

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [185]:
np.eye(3,3) # birlik matritsa

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [186]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [187]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [188]:
np.eye(8,4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [189]:
"Hello World"[6]

'W'