NumPy exercises

In [2]:
import numpy as np

print(np.__version__)

1.26.4


In [3]:
#np.array([0]*10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a numpy matrix of 2*2 integers, filled with ones.

In [6]:
np.ones([2, 2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

Create a numpy matrix of 3*2 float numbers, filled with ones.

In [7]:
X = np.arange(4, dtype=np.int8)

In [8]:
np.ones_like(X)

array([1, 1, 1, 1], dtype=int8)

Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [9]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int8)

In [10]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

Create a numpy matrix of 4*4 integers, filled with fives.

In [11]:
np.ones([4, 4], dtype=np.int8) *5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [13]:
X = np.array([[2, 3], [6, 2]], dtype=np.int8) 
np.ones_like(X)*7

array([[7, 7],
       [7, 7]], dtype=int8)

Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.


In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a numpy array, filled with 3 random integer values between 1 and 10.

In [17]:
np.random.randint(10, size=3)

array([6, 2, 9])

Create a 3*3*3 numpy matrix, filled with random float values.


In [19]:
np.random.random((3,3,3))

array([[[0.53647214, 0.70929419, 0.20693411],
        [0.12231518, 0.7953098 , 0.41984889],
        [0.2852997 , 0.8947329 , 0.76099331]],

       [[0.40737264, 0.25508711, 0.06245199],
        [0.35107742, 0.52209449, 0.81697403],
        [0.43314105, 0.13637943, 0.84724169]],

       [[0.12756004, 0.88550269, 0.01158115],
        [0.72820737, 0.87319738, 0.93033604],
        [0.63774573, 0.59867138, 0.3707366 ]]])

In [24]:
np.random.random((3, 4, 2)) #balandlik, satr, ustun

array([[[0.29023281, 0.35832791],
        [0.54944731, 0.16516135],
        [0.5723937 , 0.82651827],
        [0.55495441, 0.13323642]],

       [[0.64309838, 0.99473446],
        [0.99738511, 0.17249101],
        [0.11602838, 0.57073677],
        [0.18744241, 0.66665419]],

       [[0.41831942, 0.60151347],
        [0.91997556, 0.36409104],
        [0.70489759, 0.50860131],
        [0.66581772, 0.01931737]]])

In [25]:
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 1.75869246,  0.701548  , -0.93458551],
        [ 0.42865944,  0.09763157, -1.16816471],
        [-2.1588317 ,  0.14553372,  1.17250433]],

       [[ 0.62564702,  1.01827509,  1.21796545],
        [-0.57046574,  0.33176699, -0.19783077],
        [-2.55018535, -1.6605551 , -0.09183642]],

       [[ 0.26905606, -0.97953379,  2.46851956],
        [-0.00940319, -0.37911158, -0.86726804],
        [-0.48761081,  1.21343029, -1.30646799]]])

In [26]:
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 0.08582628,  0.24449835, -0.98919539],
        [ 1.20351303,  0.65307221,  0.02772119],
        [ 2.37031762,  1.77990024,  0.63598101]],

       [[ 1.28497844,  2.88401418, -0.12347198],
        [ 3.5687288 ,  1.96656797,  2.17853889],
        [ 2.21164544,  0.26993731,  0.02336571]],

       [[ 1.99418763, -1.35210493, -1.23831346],
        [ 0.66392875, -0.30576359,  1.59970396],
        [ 0.10731384, -0.29485199,  0.04700711]]])

Given the X python list convert it to an Y numpy array


In [27]:
X = [1, 2, 3]
Y = np.array(X)

In [28]:
Y

array([1, 2, 3])

Given the X numpy array, make a copy and store it on Y.
X numpy massivini hisobga olgan holda, nusxasini yarating va uni Y da saqlang.

In [35]:
X = np.array([1, 2, 3], dtype=np.int8)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) #different id

[1 2 3] 1329276456464
[1 2 3] 1329276455312


Create a numpy array with numbers from 1 to 10


In [36]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a numpy array with the odd numbers between 1 to 10

In [37]:
np.arange(1,11, 2)

array([1, 3, 5, 7, 9])

Create a numpy array with numbers from 1 to 10, in descending order.
1 dan 10 gacha bo'lgan raqamlardan kamayish tartibida numpy massiv yarating.

In [38]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [39]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [42]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Show the memory size of the given Z numpy matrix

In [46]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [47]:
Z.size

100

In [48]:
Z.itemsize

8

Array indexation

Given the X numpy array, show it's first element

In [49]:
X = np.array(['A','B','C','D','E'])
X[0]

'A'

Given the X numpy array, show it's last element


In [51]:
X = np.array(['A','B','C','D','E'])
X[len(X)-1]

'E'

In [52]:
X[-1]

'E'

Given the X numpy array, show it's first three elements

In [53]:
X = np.array(['A','B','C','D','E'])

X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

Given the X numpy array, show the elements in reverse position


In [54]:
X = np.array(['A','B','C','D','E'])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

Given the X numpy array, show the elements in an odd position

In [55]:
X = np.array(['A','B','C','D','E'])
X[[0, 2, -1]]

array(['A', 'C', 'E'], dtype='<U1')

In [57]:
X[::2] 

array(['A', 'C', 'E'], dtype='<U1')

Given the X numpy matrix, show the first row elements


In [58]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

Given the X numpy matrix, show the last row elements

In [59]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]


array([13, 14, 15, 16])

Given the X numpy matrix, show the first element on first row

In [60]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0][0]

1

In [61]:
X[0, 0]

1

Given the X numpy matrix, show the last element on last row

In [63]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1][-1]

16

In [64]:
X[-1, -1]

16

Given the X numpy matrix, show the middle row elements

In [66]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong

In [67]:
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

Given the X numpy matrix, show the first two elements on the first two rows

In [68]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
X[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [69]:
X[:2, :2]

array([[1, 2],
       [5, 6]])

Given the X numpy matrix, show the last two elements on the last two rows


In [73]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

Array manipulation

Convert the given integer numpy array to float

In [76]:
X = [-5, -3, 0, 10, 40]

np.array(X, dtype=np.float64)

array([-5., -3.,  0., 10., 40.])

Reverse the given numpy array (first element becomes last)


In [78]:
X = [-5, -3, 0, 10, 40]
X[::-1]

[40, 10, 0, -3, -5]

Order (sort) the given numpy array


In [79]:
X = [-5, -3, 0, 10, 40]
X.sort()

In [80]:
X

[-5, -3, 0, 10, 40]

Given the X numpy array, set the fifth element equal to 1

In [81]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Given the X numpy array, change the 50 with a 40


In [82]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

Given the X numpy matrix, change the last row with all 1


In [83]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1,1,1,1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

Given the X numpy matrix, change the last item on the last row with a 0

In [84]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1,-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

Given the X numpy matrix, add 5 to every element

In [85]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

Boolean arrays (also called masks)

Given the X numpy array, make a mask showing negative elements


In [87]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [88]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

Given the X numpy array, get numbers higher than the elements mean

In [89]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = X > X.mean()

In [90]:
X[mask]

array([ 2,  5,  6, 10])

Given the X numpy array, get numbers equal to 2 or 10

In [92]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

Logic functions

Given the X numpy array, return True if none of its elements is zero


In [93]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

Given the X numpy array, return True if any of its elements is zero


In [94]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

Summary statistics

Given the X numpy array, show the sum of its elements


In [95]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43

Given the X numpy array, show the mean value of its elements

In [96]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7

Given the X numpy matrix, show the sum of its columns

In [98]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

Given the X numpy matrix, show the mean value of its rows

In [99]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

Given the X numpy array, show the max value of its elements

In [100]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10